# Generated by Django 5.2.10 on 2026-01-24 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkademskaGodina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=20, unique=True)),
                ('naziv', models.CharField(max_length=150)),
                ('ects', models.PositiveSmallIntegerField()),
                ('godina_studija', models.PositiveSmallIntegerField()),
                ('semestar', models.PositiveSmallIntegerField(choices=[(1, 'Zimski'), (2, 'Ljetnji')])),
            ],
        ),
        migrations.CreateModel(
            name='IspitniRok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaka', models.CharField(max_length=10)),
                ('ak_godina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sas.akademskagodina')),
            ],
        ),
        migrations.CreateModel(
            name='IspitniTermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vrijeme', models.DateTimeField()),
                ('mjesto_izvodjenja', models.CharField(blank=True, max_length=120)),
                ('rok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sas.ispitnirok')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sas.predmet')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=60)),
                ('prezime', models.CharField(max_length=60)),
                ('broj_indeksa', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrijavaIspita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('prijavljen', 'Prijavljen'), ('odjavljen', 'Odjavljen')], default='prijavljen', max_length=10)),
                ('kreirano_at', models.DateTimeField(auto_now_add=True)),
                ('odjavljeno_at', models.DateTimeField(blank=True, null=True)),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sas.ispitnitermin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.student')),
            ],
        ),
        migrations.CreateModel(
            name='Uplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datum', models.DateField()),
                ('svrha', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.student')),
            ],
        ),
        migrations.CreateModel(
            name='Zaduzenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('skolarina', 'Školarina'), ('prijava_ispita', 'Prijava ispita'), ('ostalo', 'Ostalo')], max_length=20)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datum', models.DateField(auto_now_add=True)),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('povezano_sa_prijavom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sas.prijavaispita')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='ispitnitermin',
            index=models.Index(fields=['predmet', 'datum_vrijeme'], name='sas_ispitni_predmet_05f083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prijavaispita',
            unique_together={('student', 'termin')},
        ),
    ]
