# Generated by Django 5.2.10 on 2026-02-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akademskagodina',
            options={'verbose_name': 'AkademskaGodina', 'verbose_name_plural': 'Akademske Godine'},
        ),
        migrations.AlterModelOptions(
            name='ispitnirok',
            options={'verbose_name': 'IspitniRok', 'verbose_name_plural': 'Ispitni Rokovi'},
        ),
        migrations.AlterModelOptions(
            name='ispitnitermin',
            options={'verbose_name': 'IspitniTermin', 'verbose_name_plural': 'Ispitni Termini'},
        ),
        migrations.AlterModelOptions(
            name='predmet',
            options={'verbose_name': 'Predmet', 'verbose_name_plural': 'Predmeti'},
        ),
        migrations.AlterModelOptions(
            name='prijavaispita',
            options={'verbose_name': 'PrijavaIspita', 'verbose_name_plural': 'Prijave Ispita'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Studenti'},
        ),
        migrations.AlterModelOptions(
            name='uplata',
            options={'verbose_name': 'Uplata', 'verbose_name_plural': 'Uplate'},
        ),
        migrations.AlterModelOptions(
            name='zaduzenje',
            options={'verbose_name': 'Zaduzenje', 'verbose_name_plural': 'Zaduzenja'},
        ),
    ]
